FileSystem.Unix.cs: use "== null" instead of "is null"
mcs has problems with this new C# feature: "error CS1644: Feature `pattern matching' cannot be used because it is not part of the C# 7.3 language specification"